"""
Django settings for Liederweb project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


import os
from pathlib import Path
from dotenv import load_dotenv

import logging 
import logging.handlers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / "settings.env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# ---- ENVIRONMENT ----
APP_ENV = os.environ.get("APP_ENV", "dev") #podle settings.env, defaultně dev. 


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY není nastaven.")




# SECURITY WARNING: don't run with debug turned on in production!

SECURITY_LOG_FILE = "/srv/log/security.log"
TRAFFIC_LOG_FILE = "/srv/log/traffic.log"
STAFF_AUDIT_LOG_FILE = "/srv/log/staff_audit.log"

DEBUG = APP_ENV == "dev"

if APP_ENV == "prod":
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "%(asctime)s | %(levelname)s | %(name)s | %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
            "security_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": SECURITY_LOG_FILE,
                "maxBytes": 1024 * 1024 * 5,  # 5 MB
                "backupCount": 5,
                "formatter": "verbose",
                "encoding": "utf-8",
            },
            "traffic_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": TRAFFIC_LOG_FILE,
                "maxBytes": 1024 * 1024 * 5,
                "backupCount": 5,
                "formatter": "verbose",
                "encoding": "utf-8",
            },
            "staff_audit_file": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": STAFF_AUDIT_LOG_FILE,
                "maxBytes": 1024 * 1024 * 5,
                "backupCount": 10,
                "formatter": "verbose",
                "encoding": "utf-8",
                },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "loggers": {
            "django.request": {
                "handlers": ["console"],
                "level": "ERROR",
                "propagate": False,
            },
            "django": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": True,
            },
            "liederweb.security": {
                "handlers": ["security_file", "console"],
                "level": "WARNING",
                "propagate": False,
            },
            "liederweb.traffic": {
                "handlers": ["traffic_file"],
                "level": "INFO",
                "propagate": False,
            },
            "liederweb.staff_audit": {
                "handlers": ["staff_audit_file"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }
else:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "%(levelname)s | %(name)s | %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "loggers": {
            "liederweb.security": {
                "handlers": ["console"],
                "level": "WARNING",
                "propagate": False,
            },
            "liederweb.traffic": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "liederweb.staff_audit": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }

# na Produkci - nastavené ALLOWED_HOSTS
if APP_ENV == "prod":
    ALLOWED_HOSTS = ["liedersociety.website", "www.liedersociety.website", "liederweb-8885.rostiapp.cz", "www.liederweb-8885.rostiapp.cz"]
    CSRF_TRUSTED_ORIGINS = ["https://liedersociety.website", "https://www.liedersociety.website", "https://liederweb-8885.rostiapp.cz"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rozesilac',
    'core',
    'events',
    'media_assets',
    'social_feed',
    'content',
    'anymail'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "core.middleware.StaffAuditMiddleware",
    "core.middleware.SiteVisitStatsMiddleware",
]

ROOT_URLCONF = 'Liederweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Liederweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if APP_ENV == "prod":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


LOGIN_URL = 'core:login'
LOGIN_REDIRECT_URL = '/rozesilac/'
LOGOUT_REDIRECT_URL = '/core:login/'


# na produkci mailgun pro registraci, Brevo pro rozesilac, na dev emaily do konzole

NEWSLETTER_DEFAULT_FROM_EMAIL = "newsletter@liedersociety.cz"
NEWSLETTER_BASE_URL = "https://liedersociety.website"

ANYMAIL = {
    "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.environ.get("MAILGUN_DOMAIN"),
    "MAILGUN_API_URL": "https://api.eu.mailgun.net/v3",
}

ALLOWED_FROM_EMAILS = [
    ("info@liedersociety.cz", "Lieder Society"),
    ("newsletter@liedersociety.cz", "Newsletter Lieder Society")
]

if APP_ENV == "prod":

    EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
    DEFAULT_FROM_EMAIL = "info@liedersociety.cz"

    BREVO_API_KEY = os.environ.get("BREVO_API_KEY")
    BREVO_API_URL = "https://api.brevo.com/v3/smtp/email"
else:
    # dočasně vypneme EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "tmp" / "emails"
    DEFAULT_FROM_EMAIL = "local@test.project"

#zatím jen mně, ale to se musí změnit :)
VIP_NOTIFICATION_EMAILS = ["info@lieder-society.cz", "vanek.hv@gmail.com"]



FACEBOOK_PAGE_ACCESS_TOKEN = os.getenv("FACEBOOK_PAGE_ACCESS_TOKEN", "")


BREVO_DAILY_EMAIL_LIMIT = 300
NEWSLETTER_SCHEDULED_CAMPAIGN_MIN_GAP_MINUTES = 5



# věci spojené s platebním formulářem pro Tyrrell landing page - možná se to pak smaže, pokud se to nepoužije.
LIEDER_DONATION_IBAN = os.getenv("LIEDER_DONATION_IBAN", "")
LIEDER_DONATION_ACCOUNT_DISPLAY = os.getenv("LIEDER_DONATION_ACCOUNT_DISPLAY", "")
LIEDER_DONATION_RECIPIENT = os.getenv("LIEDER_DONATION_RECIPIENT", "Lieder Society z.s.")