# Generated by Django 5.2.12 on 2026-04-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rozesilac', '0004_emailcampaign_from_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('public_text', models.TextField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('vip_enabled', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VipReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_reservations', to='rozesilac.emailcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_reservations', to='rozesilac.contact')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vip_reservations', to='rozesilac.emaildelivery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_reservations', to='events.event')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'contact'), name='unique_vip_reservation_per_event_contact')],
            },
        ),
    ]
