# Generated by Django 5.2.12 on 2026-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipreservation',
            name='ticket_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Počet vstupenek'),
        ),
    ]
