# Generated by Django 5.2.12 on 2026-04-12 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_vipreservation_ticket_count'),
        ('rozesilac', '0005_emailcampaign_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-starts_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='event',
            name='duration_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='educational_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_hero', to='rozesilac.emailimage'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_secondary', to='rozesilac.emailimage'),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='theme_color',
            field=models.CharField(default='#7B2738', max_length=7, validators=[django.core.validators.RegexValidator(message='Zadej barvu ve formátu #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_label',
            field=models.CharField(blank=True, default='Koupit vstupenky', max_length=80),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_poster', to='rozesilac.emailimage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventPracticalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('info_type', models.CharField(choices=[('drinks', 'Nápoje do sálu'), ('clap', 'Tleskejte, když chcete'), ('phones', 'Mobily na silent'), ('arrival', 'Přijďte včas'), ('dress', 'Dress code není nutný'), ('other', 'Jiné')], default='other', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_infos', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('composer', models.CharField(blank=True, max_length=200)),
                ('work_title', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('info_url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('wiki', 'Wikipedia'), ('article', 'Článek'), ('video', 'Video'), ('playlist', 'Playlist'), ('other', 'Jiný odkaz')], default='article', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='events.event')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.event')),
                ('logo_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sponsor_logos', to='rozesilac.emailimage')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
