# Generated by Django 5.2.12 on 2026-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_event_duration_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_image_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center', 'Uprostřed'), ('bottom', 'Dole')], default='center', max_length=10),
        ),
    ]
