# Generated by Django 5.2.12 on 2026-04-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_hero_image_position'),
        ('rozesilac', '0005_emailcampaign_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventartist',
            name='photo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_artist_photos', to='rozesilac.emailimage'),
        ),
    ]
