# Generated by Django 5.2.12 on 2026-04-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventartist_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventartist',
            name='photo_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center', 'Uprostřed'), ('bottom', 'Dole')], default='center', max_length=10),
        ),
    ]
