# Generated by Django 5.2.12 on 2026-04-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventartist_photo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_parallax_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
