# Generated by Django 5.2.12 on 2026-04-16 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_hero_parallax_enabled'),
        ('rozesilac', '0005_emailcampaign_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Generování vstupenek povoleno')),
                ('header_text', models.CharField(default='VSTUPENKA', max_length=80, verbose_name="Nadpis na vstupence (defaultně prostě 'VSTUPENKA')")),
                ('ticket_title', models.CharField(blank=True, help_text='Finální text pro tisk. Při založení se může předvyplnit z názvu koncertu.', max_length=255, verbose_name='Název akce na vstupence')),
                ('ticket_artists_text', models.TextField(blank=True, help_text='Finální text pro tisk. Může být na jeden nebo dva řádky', verbose_name='Interpreti na vstupence')),
                ('ticket_venue_text', models.CharField(blank=True, help_text='Např. „Muzeum Bedřicha Smetany“', max_length=255, verbose_name='Místo na vstupence')),
                ('ticket_datetime_text', models.CharField(blank=True, help_text='Např. „15. března 2026 od 18:00 hod“', max_length=255, verbose_name='Datum a čas na vstupence')),
                ('default_tickets_per_page', models.PositiveSmallIntegerField(choices=[(4, '4 vstupenky na A4'), (5, '5 vstupenek na A4')], default=5, verbose_name='Výchozí počet vstupenek na stránku (podle počtu řádku interpretů)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_settings', to='events.event')),
                ('logo_image', models.ForeignKey(blank=True, help_text='Když nevyplníš, může se při generování použít výchozí logo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_ticket_logo', to='rozesilac.emailimage', verbose_name='Logo LS na vstupence')),
            ],
            options={
                'verbose_name': 'Nastavení vstupenek koncertu',
                'verbose_name_plural': 'Nastavení vstupenek koncertů',
            },
        ),
    ]
