# Generated by Django 5.2.12 on 2026-04-16 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventticketsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTicketVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('discounted', 'Zlevněná'), ('full', 'Plná'), ('honorary', 'Čestná')], max_length=20, verbose_name='Typ vstupenky')),
                ('name', models.CharField(help_text='Např. „Zlevněné vstupné“, „Plné vstupné“, „Čestná vstupenka“.', max_length=100, verbose_name='Název varianty')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Volitelné. U čestné vstupenky může zůstat prázdné.', max_digits=8, null=True, verbose_name='Cena')),
                ('ticket_price_text', models.CharField(blank=True, help_text='Např. „Cena: 150 Kč“ nebo „Čestná vstupenka“.', max_length=120, verbose_name='Text na vstupence')),
                ('allow_personalization', models.BooleanField(default=False, help_text='Zapni u varianty, která se může generovat se jménem hosta.', verbose_name='Povolit personalizaci')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_variants', to='events.event')),
            ],
            options={
                'verbose_name': 'Varianta vstupenky',
                'verbose_name_plural': 'Varianty vstupenek',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'code'), name='unique_ticket_variant_per_event_code')],
            },
        ),
    ]
