# Generated by Django 5.2.12 on 2026-04-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventticketvariant'),
        ('rozesilac', '0005_emailcampaign_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticketsettings',
            name='default_tickets_per_page',
            field=models.PositiveSmallIntegerField(choices=[(4, '4 vstupenky na A4'), (5, '5 vstupenek na A4')], default=5, verbose_name='Výchozí počet vstupenek na stránku (asi podle počtu řádku interpretů aby se to vešlo na A4)'),
        ),
        migrations.AlterField(
            model_name='eventticketsettings',
            name='logo_image',
            field=models.ForeignKey(blank=True, help_text='Když nevyplníš, při generování se použije výchozí logo LS (takže asi nevyplňuj - jenom kdybys chtěla jiné logo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_ticket_logo', to='rozesilac.emailimage', verbose_name='Logo na vstupence'),
        ),
        migrations.AlterField(
            model_name='eventticketsettings',
            name='ticket_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Název akce na vstupence'),
        ),
        migrations.AlterField(
            model_name='eventticketsettings',
            name='ticket_venue_text',
            field=models.CharField(blank=True, help_text='Např. „Muzeum Bedřicha Smetany“', max_length=255, verbose_name='Místo konání koncertu na vstupence'),
        ),
    ]
