# Generated by Django 5.2.12 on 2026-04-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventticketsettings_default_tickets_per_page_and_more'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_hero_asset', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_poster_asset', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_secondary_asset', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='eventartist',
            name='logo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sponsor_logo_assets', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='eventticketsettings',
            name='logo_asset',
            field=models.ForeignKey(blank=True, help_text='Když nevyplníš, při generování se použije výchozí logo LS (takže asi nevyplňuj - jenom kdybys chtěla jiné logo).', limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_as_ticket_logo_asset', to='media_assets.mediaasset', verbose_name='Logo na vstupence'),
        ),
    ]
