# Generated by Django 5.2.12 on 2026-04-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_hero_asset_event_poster_asset_and_more'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventartist',
            name='logo_asset',
        ),
        migrations.AddField(
            model_name='eventartist',
            name='photo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_artist_photo_assets', to='media_assets.mediaasset'),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='logo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_sponsor_logo_assets', to='media_assets.mediaasset'),
        ),
    ]
