# Generated by Django 5.2.12 on 2026-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_eventartist_logo_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipreservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zrušeno'),
        ),
        migrations.AddField(
            model_name='vipreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Aktivní'), ('cancelled', 'Zrušeno hostem')], db_index=True, default='active', max_length=20, verbose_name='Stav'),
        ),
    ]
