# Generated by Django 5.2.12 on 2026-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_vipreservation_cancelled_at_vipreservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventprogramitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
