# Generated by Django 5.2.12 on 2026-06-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_eventprogramitem_note'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
                ('image_asset', models.ForeignKey(limit_choices_to={'asset_type': 'image', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='event_gallery_images', to='media_assets.mediaasset')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
