# Generated by Django 5.2.12 on 2026-08-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipFollowupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Zobrazovat následnou výzvu')),
                ('heading', models.CharField(default='Pomozte nám natočit CD písní Agnes Tyrrell', max_length=200, verbose_name='Nadpis')),
                ('text', models.TextField(default='Pokud byste chtěli Lieder Society podpořit i jinak, budeme vděční za příspěvek do veřejné sbírky na natočení CD písní skladatelky Agnes Tyrrell.', verbose_name='Text')),
                ('button_text', models.CharField(default='Podpořit natočení CD', max_length=100, verbose_name='Text tlačítka')),
                ('button_url', models.CharField(default='/agnes-tyrrell/#podpora', max_length=500, verbose_name='Odkaz tlačítka')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nastavení následné VIP výzvy',
                'verbose_name_plural': 'nastavení následné VIP výzvy',
            },
        ),
    ]
