# Generated by Django 5.2.12 on 2026-04-22 12:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('slug', models.SlugField(blank=True, help_text='Nech prázdné pro automatické vytvoření z jména.', max_length=220, unique=True, verbose_name='Slug')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.person_photo_upload_to, verbose_name='Fotografie')),
                ('role_short', models.CharField(blank=True, help_text='Např. sopranistka, klavírista, dramaturgyně, produkce…', max_length=255, verbose_name='Role / krátký popis')),
                ('bio', models.TextField(blank=True, verbose_name='Text profilu')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Kontaktní e-mail')),
                ('website_url', models.URLField(blank=True, verbose_name='Osobní web')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Nižší číslo = zobrazí se dříve.', verbose_name='Pořadí')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy upraveno')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Lidé',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
