# Generated by Django 5.2.12 on 2026-04-25 18:40

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_facebook_url_person_instagram_url_and_more'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profiles', to='media_assets.mediaasset', verbose_name='Fotografie z mediální knihovny'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.person_photo_upload_to, verbose_name='Fotografie (staré)'),
        ),
    ]
