# Generated by Django 5.2.12 on 2026-05-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_photo_asset_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_list_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center', 'Uprostřed'), ('bottom', 'Dole')], default='center', help_text='Použije se ve veřejném výpisu lidí. Hodí se u fotek oříznutých moc vysoko nebo nízko.', max_length=10, verbose_name='Zarovnání náhledu fotky'),
        ),
    ]
