# Generated by Django 5.2.12 on 2026-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_photo_list_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_detail_layout',
            field=models.CharField(choices=[('stretch', 'Podle výšky textu'), ('contained', 'Omezená výška')], default='stretch', help_text='Výchozí volba zachová na stránce s detailem umělce vysoký výřez fotky podle délky textu. vypadá to fakt dobře imho. Omezená výška se hodí u dlouhých profilů, kde je hodně textu a kde je tudíž fotka až příliš přiblížená a nevypadá to dobře.', max_length=20, verbose_name='Chování detailové fotky'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_detail_position',
            field=models.CharField(choices=[('left', 'Vlevo'), ('center-left', 'Mírně vlevo'), ('center', 'Uprostřed'), ('center-right', 'Mírně vpravo'), ('right', 'Vpravo')], default='center', help_text='Použije se na detailu osoby. Pomáhá u fotek, kde je obličej moc vlevo nebo vpravo.', max_length=20, verbose_name='Zarovnání detailové fotky'),
        ),
    ]
