# Generated by Django 5.2.12 on 2026-05-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_photo_detail_layout_and_more'),
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo_detail_layout',
            field=models.CharField(choices=[('stretch', 'Podle výšky textu'), ('contained', 'Omezená výška')], default='stretch', help_text='Výchozí volba zachová na stránce s detailem umělce vysoký výřez fotky podle délky textu - vypadá to fakt dobře imho. Alternativně volbu "omezená výška" vyber u dlouhých profilů, kde je hodně textu a kde je tudíž fotka až příliš přiblížená a nevypadá to dobře. Ale dycky bych nejdřív zkusil tu první variantu.', max_length=20, verbose_name='Chování detailové fotky'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_detail_position',
            field=models.CharField(choices=[('left', 'Vlevo'), ('center-left', 'Mírně vlevo'), ('center', 'Uprostřed'), ('center-right', 'Mírně vpravo'), ('right', 'Vpravo')], default='center', help_text='Použije se na stránce s detailem umělce. Pomáhá u fotek, kde je obličej moc vlevo nebo vpravo. Pokud máš v poli výš vybráno "podle výšky textu " (což doporučuju), ale obličej není dobře vidět, tak tady můžeš zkusit nastavit zarovnání detailové fotky. Pokud ani to nepomůže, tak pak v tom poli výš holt vyber "omezená výška".', max_length=20, verbose_name='Zarovnání detailové fotky'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo_list_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center', 'Uprostřed'), ('bottom', 'Dole')], default='center', help_text='Použije se ve veřejném výpisu umělců (ne na stránce s detailem umělce). Hodí se u fotek oříznutých moc vysoko nebo nízko.', max_length=10, verbose_name='Zarovnání náhledu fotky'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Název partnera')),
                ('website_url', models.URLField(blank=True, verbose_name='Web partnera')),
                ('alt_text', models.CharField(blank=True, help_text='Pokud zůstane prázdné, použije se název partnera.', max_length=200, verbose_name='Alternativní text loga')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Pořadí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zobrazovat na webu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('logo', models.ForeignKey(help_text='Vyber logo z mediální knihovny.', on_delete=django.db.models.deletion.PROTECT, related_name='partner_logos', to='media_assets.mediaasset', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partneři',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
