# Generated by Django 5.2.12 on 2026-05-10 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_person_photo_detail_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_path', models.CharField(blank=True, max_length=500)),
                ('last_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Denní návštěvník',
                'verbose_name_plural': 'Denní návštěvníci',
                'ordering': ['-day', 'visitor_hash'],
                'unique_together': {('day', 'visitor_hash')},
            },
        ),
    ]
