# Generated by Django 5.2.12 on 2026-05-26 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dailysitevisitor'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarouselManualSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='Lieder Society', max_length=120, verbose_name='Horní štítek')),
                ('title', models.CharField(blank=True, default='Vybraný vizuál', max_length=180, verbose_name='Nadpis')),
                ('subtitle', models.CharField(blank=True, default='', help_text='Například název fotografie, projektu nebo krátká informace.', max_length=220, verbose_name='Doplňující řádek')),
                ('body', models.TextField(blank=True, default='', verbose_name='Popisek')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_asset', models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset', verbose_name='Obrázek z mediální knihovny')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ruční blok homepage carouselu',
                'verbose_name_plural': 'ruční blok homepage carouselu',
            },
        ),
    ]
