# Generated by Django 5.2.12 on 2026-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homecarouselmanualslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarouselmanualslide',
            name='layout',
            field=models.CharField(choices=[('side', 'Obrázek vlevo, text vpravo'), ('stacked', 'Obrázek nahoře, text dole')], default='stacked', help_text='Pro široké fotografie většinou použijte variantu obrázek nahoře, text dole.', max_length=20, verbose_name='Rozložení slidu'),
        ),
        migrations.AlterField(
            model_name='homecarouselmanualslide',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='Doplňující řádek'),
        ),
    ]
