# Generated by Django 5.2.12 on 2026-05-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_homecarouselmanualslide_layout_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgnesSupportIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='částka')),
                ('donor_name', models.CharField(blank=True, max_length=255, verbose_name='jméno dárce')),
                ('donor_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail dárce')),
                ('donor_phone', models.CharField(blank=True, max_length=50, verbose_name='telefon')),
                ('wants_receipt', models.BooleanField(default=False, verbose_name='chce potvrzení o daru')),
                ('note', models.TextField(blank=True, verbose_name='poznámka')),
                ('variable_symbol', models.CharField(blank=True, max_length=20, unique=True, verbose_name='variabilní symbol')),
                ('status', models.CharField(choices=[('created', 'Vytvořeno'), ('paid', 'Zaplaceno'), ('cancelled', 'Zrušeno')], default='created', max_length=20, verbose_name='stav')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='zaplaceno')),
            ],
            options={
                'verbose_name': 'zájem o podporu Agnes Tyrrell',
                'verbose_name_plural': 'zájmy o podporu Agnes Tyrrell',
                'ordering': ['-created_at'],
            },
        ),
    ]
