# Generated by Django 5.2.12 on 2026-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agnessupportintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPageVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('pageviews', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day', 'path'],
                'constraints': [models.UniqueConstraint(fields=('day', 'path', 'visitor_hash'), name='unique_daily_page_visitor')],
            },
        ),
    ]
