# Generated by Django 5.2.12 on 2026-06-10 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_dailypagevisitor'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSupportPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Podpořte nás', max_length=120)),
                ('title', models.CharField(default='Pomozte nám vydat nahrávku Agnes Tyrrell', max_length=220)),
                ('body', models.TextField(default='Podpořte vznik alba věnovaného skladatelce Agnes Tyrrell a pomozte nám dostat její hudbu k novým posluchačům.')),
                ('button_label', models.CharField(default='Podpořit kampaň', max_length=120)),
                ('button_url', models.CharField(default='/agnes-tyrrell/', max_length=500)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_media', models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Homepage podpora',
                'verbose_name_plural': 'Homepage podpora',
            },
        ),
    ]
