# Generated by Django 5.2.12 on 2026-06-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homesupportpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesupportpromo',
            name='background_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center', 'Uprostřed'), ('bottom', 'Dole')], default='center', help_text='Určuje, která část fotky má být při ořezu vidět.', max_length=20, verbose_name='Pozice fotky v pozadí'),
        ),
    ]
