# Generated by Django 5.2.12 on 2026-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_homesupportpromo_background_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesupportpromo',
            name='background_position',
            field=models.CharField(choices=[('top', 'Nahoře'), ('center_top', 'Lehce nahoře'), ('center', 'Uprostřed'), ('center_bottom', 'Lehce dole'), ('bottom', 'Dole')], default='center', help_text='Určuje, která část fotky má být při ořezu vidět.', max_length=20, verbose_name='Pozice fotky v pozadí'),
        ),
    ]
