# Generated by Django 5.2.12 on 2026-06-14 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_homesupportpromo_background_position'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeQuoteSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Nižší číslo se zobrazí dříve.', verbose_name='Pořadí')),
                ('is_active', models.BooleanField(default=True, verbose_name='Zobrazit na homepage')),
                ('kicker', models.CharField(help_text='Například „Koncerty“, „Sláva! Naše první písňové CD“ nebo „Mladý salón“.', max_length=140, verbose_name='Nadpis / štítek')),
                ('quote_text', models.TextField(help_text='Text citace bez uvozovek. Uvozovky doplní šablona.', verbose_name='Citace')),
                ('author_name', models.CharField(help_text='Například Anna Šerých.', max_length=160, verbose_name='Autor citace')),
                ('source_name', models.CharField(blank=True, help_text='Například OperaPlus.cz nebo KlasikaPlus.cz.', max_length=160, verbose_name='Médium / zdroj')),
                ('source_url', models.CharField(blank=True, help_text='Volitelné. Může vést přímo na recenzi.', max_length=500, verbose_name='Odkaz na zdroj recenze')),
                ('button_label', models.CharField(blank=True, help_text='Například „Přejít na koncerty“, „Do e-shopu“ nebo „Již brzy“.', max_length=140, verbose_name='Text tlačítka')),
                ('button_url', models.CharField(blank=True, help_text='Může být relativní cesta typu /koncerty/ nebo celá externí URL.', max_length=500, verbose_name='Odkaz tlačítka')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Otevřít tlačítko v nové záložce')),
                ('background_position', models.CharField(choices=[('top', 'Nahoře'), ('center_top', 'Lehce nahoře'), ('center', 'Uprostřed'), ('center_bottom', 'Lehce dole'), ('bottom', 'Dole')], default='center', help_text='Určuje, která část fotky má být při ořezu vidět.', max_length=24, verbose_name='Pozice fotky v pozadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('background_media', models.ForeignKey(blank=True, limit_choices_to={'asset_type': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_assets.mediaasset', verbose_name='Fotka do pozadí')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Upravil')),
            ],
            options={
                'verbose_name': 'Homepage citace',
                'verbose_name_plural': 'Homepage citace',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
