# Generated by Django 5.2.12 on 2026-06-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homequoteslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('human_hits', models.PositiveIntegerField(default=0)),
                ('bot_hits', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='DailyPageTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('human_hits', models.PositiveIntegerField(default=0)),
                ('bot_hits', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-day', '-total_hits'],
                'indexes': [models.Index(fields=['day', 'path'], name='core_dailyp_day_1e4781_idx'), models.Index(fields=['day', '-total_hits'], name='core_dailyp_day_d1c2b3_idx')],
                'unique_together': {('day', 'path')},
            },
        ),
    ]
