# Generated by Django 5.2.12 on 2026-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dailysitetraffic_dailypagetraffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypagetraffic',
            name='error_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailypagetraffic',
            name='not_found_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailypagetraffic',
            name='ok_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailypagetraffic',
            name='redirect_hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
