# Generated by Django 5.2.12 on 2026-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dailypagetraffic_error_hits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypagevisitor',
            name='client_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dailysitevisitor',
            name='client_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
