# Generated by Django 5.2.12 on 2026-08-12 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dailypagevisitor_client_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('client_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_path', models.CharField(blank=True, max_length=500)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('beacons', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Denní potvrzený návštěvník',
                'verbose_name_plural': 'Denní potvrzení návštěvníci',
                'ordering': ['-day', 'visitor_hash'],
                'constraints': [models.UniqueConstraint(fields=('day', 'visitor_hash'), name='unique_daily_engaged_visitor')],
            },
        ),
    ]
