# Generated by Django 5.2.12 on 2026-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dailyengagedvisitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficVisitCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('day', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('client_hash', models.CharField(db_index=True, max_length=64)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('user_agent_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('referer_kind', models.CharField(choices=[('empty', 'Bez refereru'), ('own', 'Vlastní web'), ('search', 'Vyhledávač'), ('external', 'Externí web')], db_index=True, max_length=20)),
                ('referer_host', models.CharField(blank=True, max_length=255)),
                ('is_social_iab', models.BooleanField(db_index=True, default=False)),
                ('decision', models.CharField(choices=[('pending', 'Čeká na vyhodnocení'), ('kept', 'Ponecháno jako návštěva'), ('cleaned', 'Odstraněno post-hoc'), ('already_removed', 'Odstraněno už realtime')], db_index=True, default='pending', max_length=30)),
                ('decision_reason', models.CharField(blank=True, max_length=160)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['decision', 'created_at'], name='traffic_candidate_pending_idx'), models.Index(fields=['day', 'visitor_hash'], name='traffic_candidate_visitor_idx'), models.Index(fields=['day', 'user_agent_hash', 'path', 'referer_kind'], name='traffic_candidate_pattern_idx')],
            },
        ),
    ]
