# Generated by Django 5.2.12 on 2026-08-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_trafficvisitcandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyengagedvisitor',
            name='source',
            field=models.CharField(choices=[('other', 'Ostatní / neznámé'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyengagedvisitor',
            name='source_referer',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
