# Generated by Django 5.2.12 on 2026-08-22 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dailyengagedvisitor_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrowserVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('client_hash', models.CharField(db_index=True, max_length=64)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_path', models.CharField(blank=True, max_length=500)),
                ('last_path', models.CharField(blank=True, max_length=500)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('other', 'Ostatní'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], db_index=True, default='other', max_length=20)),
                ('source_referer', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Denní JS potvrzený návštěvník',
                'verbose_name_plural': 'Denní JS potvrzení návštěvníci',
                'ordering': ['-day', 'visitor_hash'],
                'constraints': [models.UniqueConstraint(fields=('day', 'visitor_hash'), name='unique_daily_browser_visitor')],
            },
        ),
    ]
