# Generated by Django 5.2.12 on 2026-08-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_dailybrowservisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybrowservisitor',
            name='source',
            field=models.CharField(choices=[('other', 'Ostatní'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google')], db_index=True, default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyengagedvisitor',
            name='source',
            field=models.CharField(choices=[('other', 'Ostatní / neznámé'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('google', 'Google')], db_index=True, default='other', max_length=20),
        ),
    ]
