# Generated by Django 5.2.12 on 2026-08-29 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_dailybrowservisitor_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEngagedPageVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('client_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('beacons', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('other', 'Ostatní / přímé'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('own', 'Lieder Society')], db_index=True, default='other', max_length=20)),
                ('source_referer', models.CharField(blank=True, max_length=300)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-day', 'path'],
                'constraints': [models.UniqueConstraint(fields=('day', 'path', 'visitor_hash'), name='unique_daily_engaged_page_visitor')],
            },
        ),
    ]
