# Generated by Django 5.2.12 on 2026-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_dailyengagedpagevisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficvisitcandidate',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='trafficvisitcandidate',
            name='network_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='trafficvisitcandidate',
            index=models.Index(fields=['day', 'network_hash', 'referer_kind'], name='traffic_candidate_network_idx'),
        ),
    ]
