# Generated by Django 5.2.12 on 2026-09-06 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_trafficvisitcandidate_ip_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficBotIPReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('first_flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Bot IP reputace',
                'verbose_name_plural': 'Bot IP reputace',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.AlterField(
            model_name='trafficvisitcandidate',
            name='decision',
            field=models.CharField(choices=[('pending', 'Čeká na vyhodnocení'), ('kept', 'Ponecháno jako návštěva'), ('cleaned', 'Odstraněno post-hoc'), ('already_removed', 'Odstraněno už realtime'), ('quarantined', 'Karanténa kvůli IP reputaci'), ('rehabilitated', 'Obnoveno browser beaconem')], db_index=True, default='pending', max_length=30),
        ),
    ]
