# Generated by Django 5.2.12 on 2026-09-07 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_trafficbotipreputation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficBotSubnetReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_hash', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('trigger_ip_count', models.PositiveSmallIntegerField(default=0)),
                ('first_flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_flagged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Bot subnet reputace',
                'verbose_name_plural': 'Bot subnet reputace',
                'ordering': ['-expires_at'],
            },
        ),
        migrations.AddField(
            model_name='trafficvisitcandidate',
            name='subnet_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
