# Generated by Django 5.2.12 on 2026-03-26 10:12

import django.core.validators
import django.db.models.deletion
import rozesilac.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název skupiny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skupina kontaktů',
                'verbose_name_plural': 'Skupiny kontaktů',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=250)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True, help_text='Volitelné: plain-text fallback.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preheader', models.CharField(blank=True, help_text='Krátký text zobrazovaný jako náhled emailu v inboxu', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('salutation', models.CharField(blank=True, help_text="Oslovení (např. 'Vážený pane Nováku')", max_length=100, verbose_name='Oslovení')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='contacts', to='rozesilac.contactgroup', verbose_name='Skupiny')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=250)),
                ('preheader', models.CharField(blank=True, max_length=200)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField(blank=True)),
                ('is_test', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rozesilac.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_token', models.CharField(db_index=True, default=rozesilac.models.generate_tracking_token, editable=False, max_length=64, unique=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unique_click_count', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rozesilac.emailcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='EmailClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_suspected_bot', models.BooleanField(default=False)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='rozesilac.emaildelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Název')),
                ('image', models.ImageField(upload_to='email_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), rozesilac.models.validate_email_image_size], verbose_name='Obrázek')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Velikost souboru (B)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Nahráno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Obrázek do emailu',
                'verbose_name_plural': 'Obrázky do emailu',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignTrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='rozesilac.emailcampaign')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('campaign', 'url')},
            },
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['campaign', 'status'], name='rozesilac_e_campaig_de74cb_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildelivery',
            index=models.Index(fields=['to_email'], name='rozesilac_e_to_emai_309ac5_idx'),
        ),
    ]
