# Generated by Django 5.2.12 on 2026-04-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozesilac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'Emailová kampaň', 'verbose_name_plural': 'Emailové kampaně'},
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odesílání dokončeno'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Naplánováno na'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odesílání spuštěno'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Rozpracováno'), ('scheduled', 'Naplánováno'), ('sending', 'Odesílá se'), ('sent', 'Odesláno'), ('failed', 'Selhalo'), ('cancelled', 'Zrušeno')], db_index=True, default='draft', max_length=20, verbose_name='Stav'),
        ),
    ]
