# Generated by Django 5.2.12 on 2026-04-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozesilac', '0002_alter_emailcampaign_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to='rozesilac.contact', verbose_name='Kontakt'),
        ),
    ]
