# Generated by Django 5.2.12 on 2026-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozesilac', '0003_emaildelivery_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Odesílatel'),
        ),
    ]
