# Generated by Django 5.2.12 on 2026-04-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('rozesilac', '0004_emailcampaign_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='events.event', verbose_name='Koncert'),
        ),
    ]
