# Generated by Django 5.2.12 on 2026-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozesilac', '0005_emailcampaign_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Chráněnou skupinu nelze smazat.', verbose_name='Chráněná skupina'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='system_code',
            field=models.SlugField(blank=True, help_text='Interní kód pro systémové skupiny. Běžně nevyplňovat.', max_length=80, null=True, unique=True, verbose_name='Systémový kód'),
        ),
    ]
