# Generated by Django 5.2.12 on 2026-05-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozesilac', '0006_contactgroup_is_protected_contactgroup_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='fallback_salutation',
            field=models.CharField(default='Vážení přátelé písně', max_length=120, verbose_name='Oslovení pro kontakty bez oslovení'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='fallback_salutation',
            field=models.CharField(default='Vážení přátelé písně', help_text='Použije se jako {{ osloveni }}, pokud kontakt nemá vlastní oslovení.', max_length=120, verbose_name='Oslovení pro kontakty bez oslovení'),
        ),
    ]
