# Generated by Django 5.2.12 on 2026-04-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, verbose_name='Platforma')),
                ('name', models.CharField(help_text='Např. Lieder Society Facebook nebo Lieder Society Instagram', max_length=255, verbose_name='Název zdroje')),
                ('external_account_id', models.CharField(help_text='Např. Facebook Page ID nebo Instagram User ID.', max_length=255, unique=True, verbose_name='Externí ID účtu / stránky')),
                ('profile_url', models.URLField(blank=True, verbose_name='URL profilu / stránky')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Zdroj sociálního obsahu',
                'verbose_name_plural': 'Zdroje sociálního obsahu',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_post_id', models.CharField(max_length=255, verbose_name='Externí ID postu')),
                ('message', models.TextField(blank=True, verbose_name='Text postu')),
                ('permalink_url', models.URLField(blank=True, verbose_name='Odkaz na originální post')),
                ('media_type', models.CharField(choices=[('image', 'Obrázek'), ('video', 'Video'), ('carousel', 'Carousel'), ('text', 'Text'), ('other', 'Ostatní')], default='other', max_length=20, verbose_name='Typ média')),
                ('image_url', models.URLField(blank=True, verbose_name='URL náhledového obrázku')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='URL thumbnailu')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publikováno')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='Když vypneš, post zůstane v databázi, ale nebude se nabízet na webu.', verbose_name='Viditelný')),
                ('raw_payload', models.JSONField(blank=True, help_text='Pro debug a případné budoucí rozšíření.', null=True, verbose_name='Raw odpověď API')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy synchronizováno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno v databázi')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_feed.socialsource', verbose_name='Zdroj')),
            ],
            options={
                'verbose_name': 'Post ze sociální sítě',
                'verbose_name_plural': 'Posty ze sociálních sítí',
                'ordering': ['-published_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_post_id'), name='unique_social_post_per_source')],
            },
        ),
    ]
