# Generated by Django 5.2.12 on 2026-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=1500, verbose_name='URL náhledového obrázku'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='permalink_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Odkaz na originální post'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1500, verbose_name='URL thumbnailu'),
        ),
        migrations.AlterField(
            model_name='socialsource',
            name='profile_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL profilu / stránky'),
        ),
    ]
