# Generated by Django 5.2.12 on 2026-05-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0002_alter_socialpost_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_media_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Externí ID média')),
                ('media_type', models.CharField(choices=[('image', 'Obrázek'), ('video', 'Video'), ('other', 'Ostatní')], default='image', max_length=20, verbose_name='Typ média')),
                ('media_url', models.URLField(blank=True, max_length=1500, verbose_name='URL média')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1500, verbose_name='URL thumbnailu')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Pořadí')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='social_feed.socialpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Médium postu',
                'verbose_name_plural': 'Média postů',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_media_id__isnull', False)), fields=('post', 'external_media_id'), name='unique_social_media_per_post')],
            },
        ),
    ]
