# Generated by Django 5.2.12 on 2026-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0003_socialpostmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='message_tags',
            field=models.JSONField(blank=True, default=list, help_text='Normalizované message_tags z Facebook Graph API.', verbose_name='Tagy / zmínky v textu'),
        ),
    ]
