# Generated by Django 5.2.12 on 2026-06-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0004_socialpost_message_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostmedia',
            name='has_audio',
            field=models.BooleanField(blank=True, db_index=True, help_text='Vyplňuje synchronizace u video souborů. None = neověřeno.', null=True, verbose_name='Video má audio stopu'),
        ),
    ]
