# Generated by Django 5.2.12 on 2026-06-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0005_socialpostmedia_has_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpostmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
