# Generated by Django 5.2.12 on 2026-06-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_feed', '0006_socialpostmedia_height_socialpostmedia_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpostmedia',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Odkaz na médium na Facebooku'),
        ),
    ]
