# Generated by Django 5.2.12 on 2026-07-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='název')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='krátký popis')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('is_published', models.BooleanField(default=False, verbose_name='zveřejněno')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shop_products_as_main_image', to='media_assets.mediaasset', verbose_name='hlavní obrázek')),
            ],
            options={
                'verbose_name': 'produkt',
                'verbose_name_plural': 'produkty',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='alternativní text')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_product_images', to='media_assets.mediaasset', verbose_name='obrázek')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='shop.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'obrázek produktu',
                'verbose_name_plural': 'obrázky produktu',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('product', 'image'), name='unique_shop_image_per_product')],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='název varianty')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='kód produktu')),
                ('fulfilment_type', models.CharField(choices=[('physical', 'Fyzický produkt'), ('digital', 'Digitální obsah'), ('ticket', 'Vstupenka')], max_length=20, verbose_name='způsob vyřízení')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena')),
                ('track_stock', models.BooleanField(default=True, verbose_name='sledovat sklad')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='počet kusů skladem')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='produkt')),
            ],
            options={
                'verbose_name': 'varianta produktu',
                'verbose_name_plural': 'varianty produktů',
                'ordering': ('sort_order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_shop_variant_name_per_product')],
            },
        ),
    ]
