# Generated by Django 5.2.12 on 2026-07-18 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True, verbose_name='číslo objednávky')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='veřejný token')),
                ('status', models.CharField(choices=[('new', 'Nová'), ('confirmed', 'Potvrzená'), ('cancelled', 'Stornovaná'), ('completed', 'Dokončená')], default='new', max_length=20, verbose_name='stav objednávky')),
                ('payment_status', models.CharField(choices=[('awaiting', 'Čeká na platbu'), ('paid', 'Zaplaceno'), ('failed', 'Platba selhala'), ('refunded', 'Vráceno'), ('cancelled', 'Platba zrušena')], default='awaiting', max_length=20, verbose_name='stav platby')),
                ('fulfilment_status', models.CharField(choices=[('unfulfilled', 'Nevyřízeno'), ('processing', 'Zpracovává se'), ('shipped', 'Odesláno'), ('completed', 'Vyřízeno')], default='unfulfilled', max_length=20, verbose_name='stav vyřízení')),
                ('first_name', models.CharField(max_length=100, verbose_name='jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='příjmení')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='ulice a číslo')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='doplnění adresy')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='město')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='PSČ')),
                ('country', models.CharField(default='CZ', max_length=2, verbose_name='země')),
                ('customer_note', models.TextField(blank=True, verbose_name='poznámka zákazníka')),
                ('requires_shipping', models.BooleanField(default=False, verbose_name='vyžaduje dopravu')),
                ('contains_digital_content', models.BooleanField(default=False, verbose_name='obsahuje digitální obsah')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='mezisoučet')),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cena dopravy')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='celková cena')),
                ('currency', models.CharField(default='CZK', max_length=3, verbose_name='měna')),
                ('newsletter_consent', models.BooleanField(default=False, verbose_name='souhlas s newsletterem')),
                ('newsletter_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='souhlas s newsletterem udělen')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='obchodní podmínky přijaty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_orders', to=settings.AUTH_USER_MODEL, verbose_name='uživatelský účet')),
            ],
            options={
                'verbose_name': 'objednávka',
                'verbose_name_plural': 'objednávky',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='název produktu')),
                ('variant_name', models.CharField(max_length=120, verbose_name='název varianty')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='kód produktu')),
                ('fulfilment_type', models.CharField(choices=[('physical', 'Fyzický produkt'), ('digital', 'Digitální obsah'), ('ticket', 'Vstupenka')], max_length=20, verbose_name='způsob vyřízení')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='jednotková cena')),
                ('quantity', models.PositiveIntegerField(verbose_name='množství')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='celkem za položku')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='objednávka')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shop.productvariant', verbose_name='varianta produktu')),
            ],
            options={
                'verbose_name': 'položka objednávky',
                'verbose_name_plural': 'položky objednávky',
                'ordering': ('id',),
            },
        ),
    ]
