# Generated by Django 5.2.12 on 2026-07-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Vytvoření objednávky'), ('state_change', 'Změna stavů'), ('cancelled', 'Storno objednávky')], max_length=30, verbose_name='akce')),
                ('description', models.CharField(max_length=500, verbose_name='popis')),
                ('order_status', models.CharField(choices=[('new', 'Nová'), ('confirmed', 'Potvrzená'), ('cancelled', 'Stornovaná'), ('completed', 'Dokončená')], max_length=20, verbose_name='stav objednávky')),
                ('payment_status', models.CharField(choices=[('awaiting', 'Čeká na platbu'), ('paid', 'Zaplaceno'), ('failed', 'Platba selhala'), ('refunded', 'Vráceno'), ('cancelled', 'Platba zrušena')], max_length=20, verbose_name='stav platby')),
                ('fulfilment_status', models.CharField(choices=[('unfulfilled', 'Nevyřízeno'), ('processing', 'Zpracovává se'), ('shipped', 'Odesláno'), ('completed', 'Vyřízeno')], max_length=20, verbose_name='stav vyřízení')),
                ('note', models.TextField(blank=True, verbose_name='poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='shop.order', verbose_name='objednávka')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='provedl')),
            ],
            options={
                'verbose_name': 'historie objednávky',
                'verbose_name_plural': 'historie objednávek',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
