# Generated by Django 5.2.12 on 2026-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bankovní převod'), ('stripe', 'Platební karta')], default='bank_transfer', max_length=30, verbose_name='způsob platby'),
        ),
    ]
