# Generated by Django 5.2.12 on 2026-07-26 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_email_error',
            field=models.TextField(blank=True, verbose_name='chyba potvrzovacího e-mailu'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='potvrzovací e-mail odeslán'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True, verbose_name='číslo faktury')),
                ('status', models.CharField(choices=[('issued', 'Vystavená'), ('cancelled', 'Stornovaná')], default='issued', max_length=20, verbose_name='stav')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datum vystavení')),
                ('due_date', models.DateField(verbose_name='datum splatnosti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='datum storna')),
                ('seller_name', models.CharField(max_length=200, verbose_name='prodávající')),
                ('seller_address', models.TextField(verbose_name='adresa prodávajícího')),
                ('seller_company_id', models.CharField(max_length=30, verbose_name='IČO prodávajícího')),
                ('seller_vat_id', models.CharField(blank=True, max_length=30, verbose_name='DIČ prodávajícího')),
                ('seller_is_vat_payer', models.BooleanField(default=False, verbose_name='prodávající je plátce DPH')),
                ('customer_name', models.CharField(max_length=200, verbose_name='zákazník')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='e-mail zákazníka')),
                ('customer_address', models.TextField(blank=True, verbose_name='adresa zákazníka')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='mezisoučet')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='doprava')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='celkem')),
                ('currency', models.CharField(default='CZK', max_length=3, verbose_name='měna')),
                ('payment_method', models.CharField(default='bank_transfer', max_length=30, verbose_name='způsob platby')),
                ('bank_account', models.CharField(max_length=100, verbose_name='číslo účtu')),
                ('iban', models.CharField(max_length=100, verbose_name='IBAN')),
                ('variable_symbol', models.CharField(max_length=20, verbose_name='variabilní symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='shop.order', verbose_name='objednávka')),
            ],
            options={
                'verbose_name': 'faktura',
                'verbose_name_plural': 'faktury',
                'ordering': ('-issued_at', '-id'),
            },
        ),
    ]
