# Generated by Django 5.2.12 on 2026-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_confirmation_email_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='objednávka expiruje'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_notification_error',
            field=models.TextField(blank=True, verbose_name='chyba upozornění staffu'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='upozornění staffu odesláno'),
        ),
    ]
