# Generated by Django 5.2.12 on 2026-08-08 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_expires_at_order_staff_notification_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='název')),
                ('code', models.SlugField(unique=True, verbose_name='kód')),
                ('method_type', models.CharField(choices=[('address', 'Doručení na adresu'), ('pickup_point', 'Výdejní místo'), ('personal', 'Osobní převzetí')], max_length=30, verbose_name='typ dopravy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivní')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shippingmethod'),
        ),
    ]
