# Generated by Django 5.2.12 on 2026-08-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('shop', '0007_shippingmethod_order_shipping_method_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'způsob dopravy', 'verbose_name_plural': 'způsoby dopravy'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_product_variants', to='media_assets.mediaasset', verbose_name='Obrázek varianty'),
        ),
    ]
