# Generated by Django 5.2.12 on 2026-08-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        ('shop', '0008_alter_shippingmethod_options_productvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='alternativní text')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_product_variant_images', to='media_assets.mediaasset', verbose_name='obrázek')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant', verbose_name='varianta')),
            ],
            options={
                'verbose_name': 'obrázek varianty produktu',
                'verbose_name_plural': 'obrázky variant produktu',
                'ordering': ('sort_order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('variant', 'image'), name='unique_shop_image_per_variant')],
            },
        ),
    ]
