# Generated by Django 5.2.12 on 2026-08-30 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_productvariant_image_productvariantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveSmallIntegerField(verbose_name='číslo stopy')),
                ('title', models.CharField(max_length=200, verbose_name='název stopy')),
                ('full_audio', models.FileField(upload_to='shop_private/audio/', verbose_name='plná MP3')),
                ('preview_audio', models.FileField(blank=True, editable=False, upload_to='shop/audio/previews/', verbose_name='30s ukázka')),
                ('preview_start_seconds', models.PositiveIntegerField(default=0, help_text='Od které sekundy začne 30sekundová ukázka.', verbose_name='začátek ukázky v sekundách')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='délka stopy v sekundách')),
                ('is_active', models.BooleanField(default=True, verbose_name='zobrazovat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='shop.product', verbose_name='album / produkt')),
                ('purchase_variant', models.OneToOneField(blank=True, help_text='Digitální varianta produktu, kterou zákazník kupuje při nákupu této jedné stopy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_track', to='shop.productvariant', verbose_name='varianta pro samostatný nákup')),
            ],
            options={
                'verbose_name': 'stopa alba',
                'verbose_name_plural': 'stopy alba',
                'ordering': ('track_number', 'id'),
                'constraints': [models.UniqueConstraint(fields=('product', 'track_number'), name='unique_shop_track_number_per_product')],
            },
        ),
    ]
