# Generated by Django 5.2.12 on 2026-08-30 16:02

import shop.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_albumtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumtrack',
            name='full_audio',
            field=models.FileField(storage=shop.storage.PrivateShopStorage(), upload_to='audio/', verbose_name='plná MP3'),
        ),
    ]
