# Generated by Django 5.2.12 on 2026-08-30 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_albumtrack_full_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumtrack',
            options={'ordering': ('disc_number', 'track_number', 'id'), 'verbose_name': 'stopa alba', 'verbose_name_plural': 'stopy alba'},
        ),
        migrations.RemoveConstraint(
            model_name='albumtrack',
            name='unique_shop_track_number_per_product',
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='audio_metadata',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='metadata MP3'),
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='disc_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='číslo disku'),
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='original_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='původní název souboru'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_full_album_download',
            field=models.BooleanField(default=False, help_text='Tato digitální varianta zpřístupní po zaplacení všechny stopy produktu.', verbose_name='celé digitální album'),
        ),
        migrations.AlterField(
            model_name='albumtrack',
            name='preview_start_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='začátek ukázky v sekundách'),
        ),
        migrations.AlterField(
            model_name='albumtrack',
            name='purchase_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_track', to='shop.productvariant', verbose_name='varianta pro samostatný nákup'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('product', 'disc_number', 'track_number'), name='unique_shop_track_per_disc'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_full_album_download', True)), fields=('product',), name='unique_full_album_variant_per_product'),
        ),
    ]
