# Generated by Django 5.2.12 on 2026-08-31 09:27

import django.db.models.deletion
import shop.storage
import uuid
from django.db import migrations, models


def populate_download_tokens(apps, schema_editor):
    Order = apps.get_model("shop", "Order")

    for order in Order.objects.all().iterator():
        order.download_token = uuid.uuid4()
        order.save(update_fields=["download_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_albumtrack_options_and_more"),
    ]

    operations = [
        # 1. Nejprve přidáme nullable pole bez unique constraintu.
        migrations.AddField(
            model_name="order",
            name="download_token",
            field=models.UUIDField(
                editable=False,
                null=True,
                verbose_name="token pro stažení digitálního obsahu",
            ),
        ),

        # 2. Každé existující objednávce vytvoříme vlastní UUID.
        migrations.RunPython(
            populate_download_tokens,
            migrations.RunPython.noop,
        ),

        # 3. Teprve potom nastavíme finální podobu pole.
        migrations.AlterField(
            model_name="order",
            name="download_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="token pro stažení digitálního obsahu",
            ),
        ),

        migrations.AddField(
            model_name="product",
            name="digital_booklet",
            field=models.FileField(
                blank=True,
                storage=shop.storage.PrivateShopStorage(),
                upload_to="booklets/",
                verbose_name="booklet k digitálnímu albu",
            ),
        ),

        migrations.AddField(
            model_name="product",
            name="digital_booklet_original_filename",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="původní název bookletu",
            ),
        ),

        migrations.CreateModel(
            name="DigitalDownloadGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("track", "MP3 stopa"),
                            ("booklet", "Booklet"),
                        ],
                        max_length=20,
                        verbose_name="typ souboru",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=200,
                        verbose_name="produkt",
                    ),
                ),
                (
                    "display_title",
                    models.CharField(
                        max_length=255,
                        verbose_name="název",
                    ),
                ),
                (
                    "storage_name",
                    models.CharField(
                        max_length=500,
                        verbose_name="soubor v privátním úložišti",
                    ),
                ),
                (
                    "download_filename",
                    models.CharField(
                        max_length=255,
                        verbose_name="název stahovaného souboru",
                    ),
                ),
                (
                    "disc_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="číslo disku",
                    ),
                ),
                (
                    "track_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="číslo stopy",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="zpřístupněno",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_grants",
                        to="shop.order",
                        verbose_name="objednávka",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="download_grants",
                        to="shop.orderitem",
                        verbose_name="položka objednávky",
                    ),
                ),
            ],
            options={
                "verbose_name": "digitální soubor objednávky",
                "verbose_name_plural": "digitální soubory objednávek",
                "ordering": (
                    "product_name",
                    "file_type",
                    "disc_number",
                    "track_number",
                    "id",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "order",
                            "file_type",
                            "storage_name",
                        ),
                        name="unique_shop_download_grant",
                    ),
                ],
            },
        ),
    ]