# Generated by Django 5.2.12 on 2026-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_download_token_product_digital_booklet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='digital_ready_email_error',
            field=models.TextField(blank=True, verbose_name='chyba e-mailu o zpřístupnění digitálního obsahu'),
        ),
        migrations.AddField(
            model_name='order',
            name='digital_ready_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='e-mail o zpřístupnění digitálního obsahu odeslán'),
        ),
    ]
