# Generated by Django 5.2.12 on 2026-09-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_digital_ready_email_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', 'Obchodní podmínky'), ('privacy', 'Ochrana osobních údajů')], db_index=True, max_length=20, verbose_name='typ dokumentu')),
                ('version', models.PositiveIntegerField(verbose_name='verze')),
                ('title', models.CharField(max_length=200, verbose_name='název')),
                ('body', models.TextField(help_text='Text se na veřejné stránce zobrazí se zachováním odstavců.', verbose_name='text dokumentu')),
                ('effective_from', models.DateField(db_index=True, verbose_name='účinné od')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='publikováno')),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='publikováno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upraveno')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_legal_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='vytvořil')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_legal_documents_published', to=settings.AUTH_USER_MODEL, verbose_name='publikoval')),
            ],
            options={
                'verbose_name': 'právní dokument',
                'verbose_name_plural': 'právní dokumenty',
                'ordering': ('document_type', '-effective_from', '-version'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='terms_document',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_orders', to='shop.shoplegaldocument', verbose_name='přijaté obchodní podmínky'),
        ),
        migrations.AddConstraint(
            model_name='shoplegaldocument',
            constraint=models.UniqueConstraint(fields=('document_type', 'version'), name='unique_shop_legal_document_version'),
        ),
    ]
