# Generated by Django 5.2.12 on 2026-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_shoplegaldocument_order_terms_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='město výdejního místa'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_country',
            field=models.CharField(blank=True, max_length=2, verbose_name='země výdejního místa'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID výdejního místa'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='výdejní místo'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PSČ výdejního místa'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='ulice výdejního místa'),
        ),
    ]
