# Generated by Django 5.2.12 on 2026-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_pickup_point_city_order_pickup_point_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplegaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Obchodní podmínky'), ('privacy', 'Ochrana osobních údajů'), ('withdrawal', 'Odstoupení od smlouvy'), ('adr', 'Mimosoudní řešení sporů')], db_index=True, max_length=20, verbose_name='typ dokumentu'),
        ),
    ]
