# Generated by Django 5.2.12 on 2026-04-25 17:38

import django.core.validators
import django.db.models.deletion
import media_assets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Nepovinné. Když necháš prázdné, doplní se podle názvu souboru.', max_length=255, verbose_name='Název')),
                ('file', models.FileField(upload_to=media_assets.models.media_asset_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'svg', 'pdf', 'mp3', 'wav', 'ogg', 'm4a', 'mp4', 'webm', 'mov', 'xls', 'xlsx', 'csv', 'doc', 'docx', 'txt'])], verbose_name='Soubor')),
                ('asset_type', models.CharField(choices=[('image', 'Obrázek'), ('document', 'Dokument'), ('audio', 'Audio'), ('spreadsheet', 'Tabulka'), ('video', 'Video'), ('other', 'Ostatní')], db_index=True, default='other', help_text='Doplňuje se automaticky podle souboru.', max_length=20, verbose_name='Typ assetu')),
                ('alt_text', models.CharField(blank=True, help_text='Používá se hlavně pro obrázky na webu.', max_length=255, verbose_name='Alt text')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('credit', models.CharField(blank=True, help_text='Např. jméno fotografa, autora ilustrace apod.', max_length=255, verbose_name='Autor / kredit')),
                ('original_filename', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Původní název souboru')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=120, verbose_name='MIME typ')),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Velikost souboru (B)')),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Šířka obrázku')),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Výška obrázku')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Umožňuje asset skrýt bez smazání.', verbose_name='Aktivní')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Nahráno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Naposledy upraveno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL, verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Mediální asset',
                'verbose_name_plural': 'Mediální assety',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
