# Generated by Django 5.2.12 on 2026-07-03 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0016_eventgalleryimage'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('gallery', 'Obrázek / galerie'), ('youtube', 'YouTube video'), ('cta', 'Tlačítko')], max_length=20, verbose_name='Typ bloku')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('text', models.TextField(blank=True, help_text='Používá se u textového bloku.', verbose_name='Text')),
                ('youtube_url', models.URLField(blank=True, help_text='Používá se u YouTube bloku.', verbose_name='YouTube URL')),
                ('button_label', models.CharField(blank=True, help_text='Používá se u tlačítkového bloku.', max_length=120, verbose_name='Text tlačítka')),
                ('button_url', models.URLField(blank=True, help_text='Používá se u tlačítkového bloku.', verbose_name='URL tlačítka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
            ],
            options={
                'verbose_name': 'Obsahový blok',
                'verbose_name_plural': 'Obsahové bloky',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Popisek')),
                ('alt_text', models.CharField(blank=True, help_text='Když zůstane prázdné, můžeme použít alt text z media assetu.', max_length=255, verbose_name='Alternativní text')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.contentblock', verbose_name='Blok')),
                ('image', models.ForeignKey(limit_choices_to={'asset_type': 'image', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='content_block_image_usages', to='media_assets.mediaasset', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Obrázek v obsahovém bloku',
                'verbose_name_plural': 'Obrázky v obsahových blocích',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('slug', models.SlugField(help_text='Používá se v URL. Např. agnes-tyrrell-pribeh-pisne.', max_length=255, unique=True, verbose_name='Slug')),
                ('author_name', models.CharField(blank=True, max_length=255, verbose_name='Autor/ka textu')),
                ('perex', models.TextField(blank=True, help_text='Krátký úvod nebo anotace článku.', verbose_name='Perex')),
                ('keywords', models.TextField(blank=True, help_text='Volitelně zadejte výrazy pro vyhledávání. Např. Agnes Tyrrell, Tyrell, Tyrel, Schumannovi.', verbose_name='Klíčová slova')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publikováno')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum publikace')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Nepovinné. Hodí se později pro výpis na stránce Objevujte.', limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_post_covers', to='media_assets.mediaasset', verbose_name='Úvodní obrázek')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_posts', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil/a')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_posts', to='events.event', verbose_name='Související koncert')),
            ],
            options={
                'verbose_name': 'Obsahový příspěvek',
                'verbose_name_plural': 'Obsahové příspěvky',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentblock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.contentpost', verbose_name='Příspěvek'),
        ),
    ]
