# Generated by Django 5.2.12 on 2026-07-06 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='button_color',
            field=models.CharField(blank=True, default='#111111', help_text='Používá se u tlačítkového bloku.', max_length=7, validators=[django.core.validators.RegexValidator(message='Barva musí být ve formátu #RRGGBB, například #111111.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Barva tlačítka'),
        ),
    ]
