# Generated by Django 5.2.12 on 2026-07-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentblock_button_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblockimage',
            name='image_fit',
            field=models.CharField(choices=[('cover', 'Vyplnit prostor / oříznout'), ('contain', 'Zobrazit celý obrázek')], default='cover', max_length=20, verbose_name='Zobrazení obrázku'),
        ),
        migrations.AddField(
            model_name='contentblockimage',
            name='image_position',
            field=models.CharField(choices=[('center center', 'Střed'), ('center top', 'Nahoře'), ('center bottom', 'Dole'), ('left center', 'Vlevo'), ('right center', 'Vpravo')], default='center center', max_length=30, verbose_name='Pozice obrázku'),
        ),
    ]
