# Generated by Django 5.2.12 on 2026-07-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentblockimage_image_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpost',
            name='cover_image_fit',
            field=models.CharField(choices=[('cover', 'Vyplnit prostor / oříznout'), ('contain', 'Zobrazit celý obrázek')], default='cover', max_length=20, verbose_name='Zobrazení úvodního obrázku'),
        ),
        migrations.AddField(
            model_name='contentpost',
            name='cover_image_position',
            field=models.CharField(choices=[('center center', 'Střed'), ('center top', 'Nahoře'), ('center bottom', 'Dole'), ('left center', 'Vlevo uprostřed'), ('right center', 'Vpravo uprostřed')], default='center center', max_length=30, verbose_name='Pozice úvodního obrázku'),
        ),
    ]
