# Generated by Django 5.2.12 on 2026-07-08 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_contentpost_cover_image_fit_and_more'),
        ('events', '0016_eventgalleryimage'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název galerie')),
                ('slug', models.SlugField(help_text='Používá se v URL. Např. agnes-tyrrell-fotogalerie.', max_length=255, unique=True, verbose_name='Slug')),
                ('cover_image_fit', models.CharField(choices=[('cover', 'Vyplnit prostor / oříznout'), ('contain', 'Zobrazit celý obrázek')], default='cover', max_length=20, verbose_name='Zobrazení úvodního obrázku')),
                ('cover_image_position', models.CharField(choices=[('center center', 'Střed'), ('center top', 'Nahoře'), ('center bottom', 'Dole'), ('left center', 'Vlevo'), ('right center', 'Vpravo')], default='center center', max_length=30, verbose_name='Pozice úvodního obrázku')),
                ('description', models.TextField(blank=True, help_text='Krátký úvodní text k fotogalerii.', verbose_name='Popis galerie')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publikováno')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum publikace')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Upraveno')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Nepovinné. Když zůstane prázdné, můžeme jako náhled použít první obrázek z galerie.', limit_choices_to={'asset_type': 'image', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_gallery_covers', to='media_assets.mediaasset', verbose_name='Úvodní obrázek galerie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content_galleries', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil/a')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_galleries', to='events.event', verbose_name='Související koncert')),
            ],
            options={
                'verbose_name': 'Fotogalerie',
                'verbose_name_plural': 'Fotogalerie',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Popisek')),
                ('alt_text', models.CharField(blank=True, help_text='Když zůstane prázdné, použije se alt text z media assetu.', max_length=255, verbose_name='Alternativní text')),
                ('image_fit', models.CharField(choices=[('cover', 'Vyplnit prostor / oříznout'), ('contain', 'Zobrazit celý obrázek')], default='cover', max_length=20, verbose_name='Zobrazení obrázku')),
                ('image_position', models.CharField(choices=[('center center', 'Střed'), ('center top', 'Nahoře'), ('center bottom', 'Dole'), ('left center', 'Vlevo'), ('right center', 'Vpravo')], default='center center', max_length=30, verbose_name='Pozice obrázku')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Pořadí')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.contentgallery', verbose_name='Galerie')),
                ('image', models.ForeignKey(limit_choices_to={'asset_type': 'image', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='content_gallery_image_usages', to='media_assets.mediaasset', verbose_name='Obrázek')),
            ],
            options={
                'verbose_name': 'Obrázek ve fotogalerii',
                'verbose_name_plural': 'Obrázky ve fotogaleriích',
                'ordering': ['position', 'id'],
            },
        ),
    ]
