# Generated by Django 5.2.12 on 2026-09-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contentgallery_contentgalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='button_open_new_tab',
            field=models.BooleanField(default=False, help_text='Pokud je zaškrtnuto, tlačítko otevře odkaz v nové záložce.', verbose_name='Otevřít odkaz v nové záložce'),
        ),
    ]
